CREATE TABLE rentals (
    rental_id INT AUTO_INCREMENT PRIMARY KEY,
    book_id INT NOT NULL,
    shop_id INT NULL,
    renter_id INT NOT NULL,
    borrower_id INT NOT NULL,
    owner_id INT NOT NULL,
    rental_plan ENUM('15days','30days') NOT NULL,
    start_date DATETIME NULL,
    due_date DATETIME NULL,
    rental_price DECIMAL(10,2) NOT NULL,
    commission_rate DECIMAL(5,4) NOT NULL DEFAULT 0.0500,
    net_rental_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    deposit_price DECIMAL(10,2) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    past_due_days INT NOT NULL DEFAULT 0,
    fine_paid_at DATETIME NULL,
    condition_fine_rate DECIMAL(4,2) NOT NULL DEFAULT 0.00,
    condition_fine_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    status ENUM('กำลังยืม', 'รอคืน', 'คืนแล้ว', 'เลยกำหนด') NOT NULL DEFAULT 'กำลังยืม',
    return_requested_at DATETIME NULL,
    return_delivery_sent_at DATETIME NULL,
    return_delivery_proof_path VARCHAR(255) NULL,
    payment_status ENUM('ชำระแล้ว','รอชำระ','ยกเลิก') NOT NULL DEFAULT 'ชำระแล้ว',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_rentals_book FOREIGN KEY (book_id) REFERENCES books(book_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_rentals_shop FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_rentals_renter FOREIGN KEY (renter_id) REFERENCES users(user_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_rentals_borrower FOREIGN KEY (borrower_id) REFERENCES users(user_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_rentals_owner FOREIGN KEY (owner_id) REFERENCES users(user_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    INDEX idx_rentals_renter (renter_id),
    INDEX idx_rentals_shop (shop_id),
    INDEX idx_rentals_owner (owner_id),
    INDEX idx_rentals_book (book_id),
    INDEX idx_rentals_status_due (status, due_date)
);
